name: Build, Test and Check Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Format
        run: clang-format --dry-run --style=Google -Werror **/*.inc **/*.hpp



  release:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      shell: bash
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Make
      run: cd ${{github.workspace}}/build && make

    - name: Test
      run: cd ${{github.workspace}}/build && ctest

  debug:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
        shell: bash
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Make
        run: cd ${{github.workspace}}/build && make

      - name: Test
        run: cd ${{github.workspace}}/build && ctest
