name: docs

on:
  push

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependencies
      run: sudo apt-get install doxygen graphviz


    - name: build docs
      run: |
        cd doc
        doxygen Doxyfile

    - name: deploy docs only if it is pushed to main
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        #publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/doxydocs/html
        force_orphan: true
